// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerApp.Models;

#nullable disable

namespace PokerApp.Migrations
{
    [DbContext(typeof(PokerContext))]
    partial class PokerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PokerApp.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.HasIndex("GameId2");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PokerApp.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerChips")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerChips")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PokerApp.Models.Card", b =>
                {
                    b.HasOne("PokerApp.Models.Game", null)
                        .WithMany("CommunityCards")
                        .HasForeignKey("GameId");

                    b.HasOne("PokerApp.Models.Game", null)
                        .WithMany("ComputerHand")
                        .HasForeignKey("GameId1");

                    b.HasOne("PokerApp.Models.Game", null)
                        .WithMany("PlayerHand")
                        .HasForeignKey("GameId2");
                });

            modelBuilder.Entity("PokerApp.Models.Game", b =>
                {
                    b.Navigation("CommunityCards");

                    b.Navigation("ComputerHand");

                    b.Navigation("PlayerHand");
                });
#pragma warning restore 612, 618
        }
    }
}
